<template>
    <div class="prime-explorer-1">
        <div class = "outer">
            <p>
                Select any numbers below and this will show you all the multiples generated by
                those factors.
            </p>
            <div 
                v-for = "num in numArray" 
                :key = "num.name"
                :class = "num.selected ? 'num-chosen' : (num.multiple ? 'num-multiple' : 'num-hidden')"
                class="num-card"
                @click = "toggleToSelected(num.name)"
            >
                {{ num.name }}
            </div>
        </div>
    </div>
</template>
<script>
export default {
    data () {
        return {
            maxNum : 200,
            numArray : [],
            products : []
        }
    },
    computed : {
        selected () {
            let arr = [];
            for (let i = 0; i < this.numArray.length; i++) {
                if (this.numArray[i].selected) {
                    arr.push(this.numArray[i]);
                }
            }
            return arr;
        },
        multiples () {
            let arr = [];
            for (let i = 0; i < this.numArray.length; i++) {
                if (this.numArray[i].multiple) {
                    arr.push(this.numArray[i]);
                }
            }
            return arr;
        }
    },
    watch : {
        selected () {
            this.updateMultiples();
        },
        products () {
            for (let i = 0; i < this.numArray.length; i++) {
                this.numArray[i].multiple = false;
            }
            for (let i = 0; i < this.products.length; i++) {
                this.products[i].multiple = true;
            }

        }
    },
    mounted () {

        for (let i = 2; i <= this.maxNum; i++) {
            this.numArray.push({
                "name" : i,
                "selected" : false,
                "multiple" : false
            });
        }
    },
    methods : {
        toggleToSelected (i) {
            let num = this.getNumByName(i);
            num.selected = !num.selected;
            if (num.selected) {
                num.multiple = true;
            }
        },
        getNumByName (name) {
            for (let i = 0; i < this.numArray.length; i++) {
                if (this.numArray[i].name == name) {
                    return this.numArray[i];
                }
            }
            return null;
        },
        addToProducts (obj) {
            for (let i = 0; i < this.products.length; i++) {
                if (this.products[i] == obj) {
                    return;
                }
            }
            this.products.push(obj);
            obj.multiple = true;
        },
        updateMultiplesRound () {
            let max = this.maxNum;
            let toAdd = [];
            for (let i = 0; i < this.products.length; i++) {
                for (let j = 0; j < this.products.length; j++) {
                    let prod = this.products[i].name * this.products[j].name ;
                    if (prod <= max) {
                        let num = this.getNumByName(prod);
                        toAdd.push(num);
                        
                    }
                }
            }
            for (let i = 0; i < toAdd.length; i++) {
                this.addToProducts(toAdd[i]);
            }

        },
        updateMultiples () {
            this.products = [];
            for (let i = 0; i < this.selected.length; i++) {
                this.addToProducts(this.selected[i]);
            }
            let currentNumMultiples;
            let test;
            do {
                currentNumMultiples = this.products.length;
                this.updateMultiplesRound();
                test = currentNumMultiples < this.products.length;
            } while (test);

        }
    }

}

</script>
<style lang="scss">
.prime-explorer-1 {

    .num-card {
        display: inline-block;
        margin: 5px;
        text-align: center;
        padding: 5px;
        font-size: 22px;
        border-style :solid;
        border-width : 1px;
        border-color : darkgray;
        border-radius : 3px;
        min-width: 3em;
        cursor: pointer;
    }

    .num-hidden {
        color: lightgray;
        border-width:3px;
    }

    .num-chosen {
        border-color: gold;
        border-width:3px;
    }
    .num-multiple {
        border-color: black;
        border-width:3px;
    }

}
</style>